/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include "CatchRobo2019.hpp"
#include "USART.hpp"
#include "SerialPort.hpp"

int main(void)
{
    PeripheralSetup();
    DeviceSetup();

    usart1_printf("usart1\n");
    usart3_printf("usart3\n");

    while(1){
        led0.toggle();
        delay_ms(50);

        //状態、状態、mailbox0の送信リクエスト、１、２、
        //usart3_printf("%d\t%d\t%d\t%d\t%d\n", (CAN2->MSR & CAN_MSR_INAK), (CAN2->MSR & CAN_MSR_SLAK), (CAN2->sTxMailBox[0].TIR & CAN_TI0R_TXRQ), (CAN2->sTxMailBox[1].TIR & CAN_TI0R_TXRQ), (CAN2->sTxMailBox[2].TIR & CAN_TI0R_TXRQ));
        for(int i = 0; i < 32; i++){
            //usart3_printf("%d ", (uint32_t)(CAN2->TSR>>(31-i) & 0x01));
            //usart3_printf("%d ", (uint32_t)(CAN2->ESR>>(31-i) & 0x01));
            //usart3_printf("%d ", (uint32_t)(CAN2->MCR>>(31-i) & 0x01));
            usart3_printf("%d ", (uint32_t)(CAN2->MSR>>(31-i) & 0x01));
        }
        //for(int i = 0; i < 6; i++){
        ////    //usart3_printf("%d ", (uint32_t)(CAN2->RF1R>>5-i) & 0x01);
        //}

        usart3_printf("\n");
        if(!button0.read()){
            requestFlag = true;
        //    led1.write(1);
        }else{
            requestFlag = false;
        //    led1.write(0);
        }
    }

    while(1){
        //safety.cycle();
        //debug.cycle();
#if defined(DISTRIBUTED_PROCESSING) || defined(CENTRALIZED_SLAVE)
        //ローカルのセンサ取得->送信
        //canNode.send();

#endif
    }
}
